base_url = "/"
compile_sass = true
title = "IT Partners"
build_search_index = true

taxonomies = [
    {name = "tags"},
    {name = "products"},
    {name = "types"}
]

[link_checker]

skip_prefixes = [
    "https://support.microsoft.com/",
    "http://www.microsoftvolumelicensing.com/",
    "https://portal.azure.com/",
    "https://support.office.com/",
    "https://cloudblogs.microsoft.com/",
]