name: merge

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz
          chmod +x zola
          ./zola check
      - uses: heytitle/github-action-yaspeller@v0.0.7
        with:
          ext: ".md"